### ISSUE TITLE
API key requested on download

### ISSUE THREAD

**Issue by aurelin** [dennmart/wanikani-to-anki#6]
I am using Chrome on Mac OS X El Capitan.

When I try to download an export, it asks me to reenter the API key. This keeps happening every time I try to get an export.

**Comment by dennmart** [comment]
@aurelin Thanks for reporting this! I ran into it as well. It seems like I had some slight misconfiguration for the server during a recent upgrade. It seems to be working now - can you confirm it's working on your end as well?

**Comment by dennmart** [comment]
@aurelin This should have been fixed and I haven't gotten any additional reports about it, so I'll close this. If you continue to have issues, feel free to reopen this or create a new issue.
